version: "0.2"
ignorePaths: []
dictionaryDefinitions:
  - name: custom-dictionary
    path: ./.cspell/custom-dictionary.txt
    addWords: true
words:
  - commitlint
  - conventionalcommits
  - partialize
  - Pressable
  - springify
  - zustand
  - tamagui
  - haptics
  - moti
import: []
